project:
  type: website
  output-dir: docs

website:
  title: "Ryan Mooney"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: ResearchProjects.qmd
        text: "Research Projects"
      - text: "Data Science"
        menu: 
          - text: "Pixar Ratings"
            href: pixar.qmd
          - text: "UNESCO World Heritage Sites"
            href: UNESCO.qmd
          - text: "Selected Literary Prizes"
            href: tidytuesday10_28.qmd
          - text: "Text Analysis"
            href: TextAnalysis.qmd
          - text: "Permutation Test"
            href: permutation.qmd
          - text: "Data Science Ethics"
            href: ethics.qmd
          - text: "SQL"
            href: SQL.qmd

  page-footer: 
    background: light 
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://https://github.com/rymooney/rymooney.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
  

format:
  html:
    theme: trestles
    css: styles.css
    toc: true
    page-layout: full

editor: visual

